Handling Imbalanced Dataset

In [1]:
import pandas as pd


In [2]:
df=pd.read_csv("creditcard.csv")

In [3]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [4]:
df.Class.value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [5]:
X=df.iloc[:, :-1]
y=df.iloc[:, -1]

Cross Validation: KFold and Hyperparameter Technique: GridSearchCV

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import KFold
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split

In [7]:
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size = 0.7)

In [11]:
log_class = LogisticRegression(solver='liblinear', max_iter=1000)  # 'liblinear' supports l1 and l2

grid = {
    'C': 10.0 ** np.arange(-2, 3),
    'penalty': ['l1', 'l2']  # Both supported by 'liblinear'
}

cv = KFold(n_splits=5, shuffle=True, random_state=42)


In [12]:
clf = GridSearchCV(log_class, grid, cv=cv, n_jobs=-1, scoring='f1_macro')
clf.fit(X_train,y_train)

GridSearchCV(cv=KFold(n_splits=5, random_state=42, shuffle=True),
             estimator=LogisticRegression(max_iter=1000, solver='liblinear'),
             n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [13]:
prediction = clf.predict(X_test)
print(confusion_matrix(y_test, prediction))
print(accuracy_score(y_test, prediction))
print(classification_report(y_test, prediction))

[[198999     30]
 [   145    191]]
0.9991222130263587
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    199029
           1       0.86      0.57      0.69       336

    accuracy                           1.00    199365
   macro avg       0.93      0.78      0.84    199365
weighted avg       1.00      1.00      1.00    199365



In [14]:
class_weight = dict({0: 1, 1: 100})

In [15]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(class_weight=class_weight)
clf.fit(X_train, y_train)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [16]:
prediction = clf.predict(X_test)
print(confusion_matrix(y_test, prediction))
print(accuracy_score(y_test, prediction))
print(classification_report(y_test, prediction))

[[199016     13]
 [    82    254]]
0.9995234870714519
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    199029
           1       0.95      0.76      0.84       336

    accuracy                           1.00    199365
   macro avg       0.98      0.88      0.92    199365
weighted avg       1.00      1.00      1.00    199365



Under Sampling

In [18]:
pip install imbalanced-learn


  Obtaining dependency information for imbalanced-learn from https://files.pythonhosted.org/packages/9d/41/721fec82606242a2072ee909086ff918dfad7d0199a9dfd4928df9c72494/imbalanced_learn-0.13.0-py3-none-any.whl.metadata
  Obtaining dependency information for sklearn-compat<1,>=0.1 from https://files.pythonhosted.org/packages/f0/a8/ad69cf130fbd017660cdd64abbef3f28135d9e2e15fe3002e03c5be0ca38/sklearn_compat-0.1.3-py3-none-any.whl.metadata
   ---------------------------------------- 0.0/238.4 kB ? eta -:--:--
   - -------------------------------------- 10.2/238.4 kB ? eta -:--:--
   ----- --------------------------------- 30.7/238.4 kB 640.0 kB/s eta 0:00:01
   --------------- ----------------------- 92.2/238.4 kB 871.5 kB/s eta 0:00:01
   ------------------- ------------------ 122.9/238.4 kB 717.5 kB/s eta 0:00:01
   -------------------------- ----------- 163.8/238.4 kB 817.0 kB/s eta 0:00:01
   ------------------------------- ------ 194.6/238.4 kB 737.3 kB/s eta 0:00:01
   ---------------


[notice] A new release of pip is available: 23.2.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [19]:
from imblearn.under_sampling import NearMiss
from collections import Counter

In [21]:
ns = NearMiss(sampling_strategy=0.8)
X_train_ns, y_train_ns = ns.fit_resample(X_train, y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_ns)))

The number of classes before fit Counter({0: 85286, 1: 156})
The number of classes after fit Counter({0: 195, 1: 156})


In [22]:
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_ns)))

The number of classes before fit Counter({0: 85286, 1: 156})
The number of classes after fit Counter({0: 195, 1: 156})


In [23]:
y_train.value_counts()

Class
0    85286
1      156
Name: count, dtype: int64

In [24]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
clf.fit(X_train_ns, y_train_ns)

RandomForestClassifier()

In [25]:
prediction = clf.predict(X_test)
print(confusion_matrix(y_test, prediction))
print(accuracy_score(y_test, prediction))
print(classification_report(y_test, prediction))

[[173037  25992]
 [    22    314]]
0.8695157123868282
              precision    recall  f1-score   support

           0       1.00      0.87      0.93    199029
           1       0.01      0.93      0.02       336

    accuracy                           0.87    199365
   macro avg       0.51      0.90      0.48    199365
weighted avg       1.00      0.87      0.93    199365



Over Sampling

In [26]:
from imblearn.over_sampling import RandomOverSampler

In [28]:
os = RandomOverSampler(sampling_strategy=0.5)
X_train_os, y_train_os = os.fit_resample(X_train, y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_os)))

The number of classes before fit Counter({0: 85286, 1: 156})
The number of classes after fit Counter({0: 85286, 1: 42643})


In [29]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
clf.fit(X_train_os, y_train_os)

RandomForestClassifier()

In [30]:
prediction = clf.predict(X_test)
print(confusion_matrix(y_test, prediction))
print(accuracy_score(y_test, prediction))
print(classification_report(y_test, prediction))

[[199009     20]
 [    74    262]]
0.9995285029970156
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    199029
           1       0.93      0.78      0.85       336

    accuracy                           1.00    199365
   macro avg       0.96      0.89      0.92    199365
weighted avg       1.00      1.00      1.00    199365



SMOTETomek

In [31]:
from imblearn.combine import SMOTETomek

In [33]:
os = SMOTETomek(sampling_strategy=0.5)
X_train_os, y_train_os = os.fit_resample(X_train, y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_os)))

The number of classes before fit Counter({0: 85286, 1: 156})
The number of classes after fit Counter({0: 84514, 1: 41871})


In [34]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
clf.fit(X_train_os, y_train_os)

RandomForestClassifier()

In [35]:
prediction = clf.predict(X_test)
print(confusion_matrix(y_test, prediction))
print(accuracy_score(y_test, prediction))
print(classification_report(y_test, prediction))

[[198985     44]
 [    62    274]]
0.9994683118902515
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    199029
           1       0.86      0.82      0.84       336

    accuracy                           1.00    199365
   macro avg       0.93      0.91      0.92    199365
weighted avg       1.00      1.00      1.00    199365

